WIP: JAPI-424 Provide compression algorithm
hpcc-systems/hpcc4j pull request #494
Opened 2021-08-04 19:38 UTC by jpmcmu

Signed-off-by: James McMullan James.McMullan@lexisnexis.com

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [X] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [X] I have created a corresponding JIRA ticket for this submission
- [X] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [X] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [X] The change has been fully tested:
  - [ ] I have performed unit tests to cover my changes.
  - [ ] I have performed system test and covered possible regressions and side effects.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [X] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.

## Testing:

2021-08-04 19:38 UTC, jpmcmu commented
@rpastrana still tracking down a few bugs

2021-08-05 14:45 UTC, rpastrana reviewed
@jpmcmu how much of this comes from "FastLZ - Byte-aligned LZ77 compression library"?
Can that logic be java imported, or submoduled from their github repo? then we can build a wrapper around it?

2021-08-06 13:12 UTC, jpmcmu commented
@rpastrana The FastLZ code is in C. There are a few ports out there but they don't have licenses attached to them. I added the license to the code I ported over to remind me to check if it needs to be included, since I used the C code as a starting point.

2021-08-31 15:53 UTC, jpmcmu commented
@rpastrana please review

2021-08-31 18:42 UTC, rpastrana commented on commons-hpcc/src/main/java/org/hpccsystems/commons/fastlz/FastLZ.java
> +/*******************************************************************************
does it make sense to name this fastLZ4j ?

2021-08-31 19:11 UTC, rpastrana requested changes
@jpmcmu added a few questions. 
Also, not all methods need a javadoc comment, but let's try to javadoc comment the 2 classes and perhaps the major methods, and perhaps a highlevel package level write up like this one:
HPCC4J\wsclient\src\main\java\org\hpccsystems\ws\client\package-info.java

2021-08-31 19:11 UTC, rpastrana commented on commons-hpcc/src/main/java/org/hpccsystems/commons/fastlz/FastLZ.java
> +            state.compressionLevel = (input[0] >> 5) + 1;
we might need to guard against empty input array

2021-08-31 19:11 UTC, rpastrana commented on commons-hpcc/src/main/java/org/hpccsystems/commons/fastlz/FastLZ.java
> +        // else...
might as well code in the "else"

2021-08-31 19:11 UTC, rpastrana commented on commons-hpcc/src/main/java/org/hpccsystems/commons/fastlz/FastLZ.java
> +        private int ip = -1;
can we use a self describing name for these vars?

2021-09-10 17:18 UTC, rpastrana approved these changes

2021-09-10 17:18 UTC, merged