HPCC4J-445 Add Junit tests for date tests
hpcc-systems/hpcc4j pull request #510
Opened 2021-11-10 20:15 UTC by rpastrana

Signed-off-by: Rodrigo Pastrana <Rodrigo.Pastrana@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [ ] I have created a corresponding JIRA ticket for this submission
- [ ] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [ ] The change has been fully tested:
  - [ ] I have performed unit tests to cover my changes.
  - [ ] I have performed system test and covered possible regressions and side effects.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.

## Testing:

2021-11-11 20:16 UTC, rpastrana commented
@jpmcmu please review

2021-11-11 20:51 UTC, jpmcmu requested changes
Found an issue with the donotquote check, and a question on expanding the test a bit. Otherwise it looks good

2021-11-11 20:51 UTC, jpmcmu commented on commons-hpcc/src/main/java/org/hpccsystems/commons/utils/Utils.java
> +                USNumberFormat.parse((String)obj);
It seems like we are missing something here. Are we checking to see if the string is a number?

2021-11-11 20:51 UTC, jpmcmu commented on dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
> +        if (records.size() == 0)
It might be a good idea to check if it can return a specific set of records as well.

2021-11-12 17:19 UTC, rpastrana commented
@jpmcmu please review latest commit

2021-11-12 20:53 UTC, jpmcmu approved these changes
@rpastrana looks good

2021-11-12 21:30 UTC, rpastrana commented
> 
> 
> @rpastrana looks good, but it looks like test is failing now?

@jpmcmu yep those changes uncovered more issues which I hopefully addressed in the latest commit. please take a look

2021-11-16 15:02 UTC, jpmcmu approved these changes
@rpastrana looks good

2021-11-16 19:11 UTC, merged