JAPI-437 TLK Indexes not filtering partitions as expected
hpcc-systems/hpcc4j pull request #511
Opened 2021-11-30 15:51 UTC by jpmcmu

- Fixed off by one error where first partition range was not created
- Added log message for invalid filters
Signed-off-by: James McMullan <James.McMullan@lexisnexis.com>

## Type of change:
- [X] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [X] I have created a corresponding JIRA ticket for this submission
- [X] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [X] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [X] The change has been fully tested:
  - [ ] I have performed unit tests to cover my changes.
  - [ ] I have performed system test and covered possible regressions and side effects.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [X] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.

## Testing:

2021-11-30 16:17 UTC, drealeed approved these changes
LGTM

2021-12-08 18:11 UTC, rpastrana requested changes
@jpmcmu a couple of minor comments

2021-12-08 18:11 UTC, rpastrana commented on dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSIndexTest.java
> +
very minor, remove blank spaces

2021-12-08 18:11 UTC, rpastrana commented on dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSIndexTest.java
> +                            hadExpectedPartition = true;
can we break out of the loop at this point?

2022-01-07 20:36 UTC, jpmcmu commented
@rpastrana implemented code review changes and squashed

2022-01-07 21:13 UTC, merged