JAPI-488 Illegal capacity error reading child dataset field in index
hpcc-systems/hpcc4j pull request #591
Opened 2022-09-16 20:07 UTC by jpmcmu

- Corrected issue with how biased integer correction for indexes was implemented.

Signed-off-by: James McMullan James.McMullan@lexisnexis.com

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [X] I have created a corresponding JIRA ticket for this submission
- [X] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [X] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [X] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [X] The change has been fully tested:
  - [ ] This change does not cause any existing JUnits to fail.
  - [ ] I have include JUnit coverage to test this change
  - [ ] I have performed system test and covered possible regressions and side effects.
- [X] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] This change fixes the problem, not just the symptom

## Testing:

2022-09-16 20:08 UTC, jpmcmu commented
@rpastrana @drealeed please review

2022-09-16 22:06 UTC, rpastrana requested changes
@jpmcmu seems fine, only a couple of minor issues

2022-09-16 22:06 UTC, rpastrana commented on commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/RecordDefinitionTranslator.java
> +                if ((typeID & TYPE_ID_MASK) == type_keyedint) {
formatting

2022-09-16 22:06 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
> +     */
minor, superfluous white-space introduced

2022-09-23 20:04 UTC, jpmcmu commented
@rpastrana please review

2022-09-23 21:25 UTC, rpastrana requested changes
@jpmcmu a few comments on the test functionality

2022-09-23 21:25 UTC, rpastrana commented on dfsclient/src/test/resources/child-index.ecl
> +childRec := RECORD
at the risk of being unnecessarily verbose, let's ensure the file name is self documenting...
generate-nested-dataset-and-index.ecl?

2022-09-23 21:25 UTC, rpastrana commented on dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
> +            List<HPCCRecord> records = readFile(file, connTO, false);
does it make sense to assert an expected number of records?

2022-09-23 21:25 UTC, rpastrana commented on dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
> +        String eclFile = "child-index.ecl";
let's externalize this functionality, maybe a function in BaseRemoteTest which loads and execute the ecl based on file name. we could execute the appropriate ecl once before the test run, and the tests should be skipped if the required datasets are not available.

2022-09-27 13:48 UTC, rpastrana approved these changes

2022-09-27 13:49 UTC, merged