JAPI-500 String trim flag when reading hpcc files
hpcc-systems/hpcc4j pull request #600
Opened 2023-02-03 22:03 UTC by jpmcmu

- Added string processing flags / code in BinaryRecordReader
- Implemented unit tests for trim / empty to null conversion

Signed-off-by: James McMullan James.McMullan@lexisnexis.com

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [X] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [X] I have created a corresponding JIRA ticket for this submission
- [X] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [X] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [X] The change has been fully tested:
  - [ ] This change does not cause any existing JUnits to fail.
  - [ ] I have include JUnit coverage to test this change
  - [ ] I have performed system test and covered possible regressions and side effects.
- [X] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] This change fixes the problem, not just the symptom

## Testing:

2023-02-03 22:15 UTC, jpmcmu commented
@rpastrana @drealeed please review

2023-02-04 00:03 UTC, drealeed approved these changes

2023-02-06 21:14 UTC, rpastrana requested changes
@jpmcmu a few minor comments

2023-02-06 21:14 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
> +
remove

2023-02-06 21:14 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
> +
let's add a public static final int      NO_STRING_TRIM= 1;

2023-02-06 21:14 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
> +    private void trimStringInScratchBuffer(boolean isUnicode, int[] range)
let's add element level comments, as discussed, see if we can use Character.isWhitespace

2023-02-06 21:14 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
> +        return new String(scratchBuffer,strRange[0],strByteLen,charset);
extra white space at end of line

2023-02-08 16:59 UTC, rpastrana approved these changes

2023-02-08 17:00 UTC, merged