HPCC4J-611 Add OpenTelemetry tracing to dfsclient
hpcc-systems/hpcc4j pull request #722
Opened 2024-07-10 13:28 UTC by jpmcmu

- Updated event attribute reporting
- Fixed trace structure in dfsclient protocol
- Added tracing to FileUtility

Signed-off-by: James McMullan James.McMullan@lexisnexis.com

## Type of change:
- [X] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [X] I have created a corresponding JIRA ticket for this submission
- [X] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [X] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [X] The change has been fully tested:
  - [ ] This change does not cause any existing JUnits to fail.
  - [ ] I have include JUnit coverage to test this change
  - [ ] I have performed system test and covered possible regressions and side effects.
- [X] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] This change fixes the problem, not just the symptom

## Testing:

2024-07-16 20:07 UTC, jpmcmu commented
@rpastrana Wrapped up code review changes, please review

2024-07-16 21:56 UTC, rpastrana requested changes
@jpmcmu looks good, but left you a few suggestions. Let's discuss.

2024-07-16 21:56 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java
> +                taskSpan = Utils.createChildSpan(taskSpan, operationName);
does it makes sense to have a single Utils.createSpan(parentSpan, spanName)? If parentSpan != null, it sets it as the parent

2024-07-16 21:56 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java
some of these context values seem worth reporting in the span

2024-07-16 21:56 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java
> +            context.setTaskSpanAttributes(Attributes.of(AttributeKey.stringKey("server.url"), connString));
is there a way to add individual attributes after this initial set attributes call?

2024-07-16 21:56 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java
> +        context.setTaskSpanAttributes(Attributes.of(AttributeKey.stringKey("server.url"), connString));
Are there other attributes we might want to report to help track issues?

2024-07-16 21:56 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java
> +            context.setTaskSpanAttributes(Attributes.of(AttributeKey.stringKey("server.src.url"), srcURL,
does the context.staroperation call add any relevant attributes to the span?

2024-07-16 21:56 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCRemoteFileWriter.java
> +        FileWriteContext context = new FileWriteContext();
do all/some of these end up tracked in a span?

2024-07-16 21:56 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/Utils.java
> +            globalOpenTelemetry = GlobalOpenTelemetry.get();
should this call setGlobalOpenTelemetry ?

2024-07-16 21:56 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/Utils.java
> +        Span span = Utils.getTelemetryTracer().spanBuilder(name)
can we combine the two functions?
Span createSpan(String name, Span parent)

2024-07-19 15:34 UTC, jpmcmu commented
@rpastrana please review

2024-07-19 17:09 UTC, rpastrana requested changes
@jpmcmu reviwed

2024-07-19 17:09 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/Utils.java
> +        Span span = Utils.getTelemetryTracer().spanBuilder(name)
are we combining these 2?

2024-07-19 17:51 UTC, jpmcmu commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java
> +        public TaskOperation getOperation()
I want all new operations to go through startOperation / endOperation. So I don't want to expose an addOperation etc

2024-07-19 18:19 UTC, rpastrana approved these changes

2024-07-19 18:23 UTC, jpmcmu commented
Tracing results from Kibana:
![Screenshot 2024-07-19 at 2 22 27 PM](https://github.com/user-attachments/assets/64cb8b01-9f2a-486d-b278-cfef5037d38d)
![Screenshot 2024-07-19 at 2 22 50 PM](https://github.com/user-attachments/assets/79682144-0305-43dd-a8b7-0dbb67610c21)

2024-07-19 20:17 UTC, jpmcmu commented
With ESP tracing enabled:
![Screenshot 2024-07-19 at 4 17 02 PM](https://github.com/user-attachments/assets/69cc7ef6-81dd-448f-abf0-25d6b7000fe5)

2024-07-19 20:22 UTC, rpastrana commented
> Tracing results from Kibana, second screenshot is the list of events under the read span. ![Screenshot 2024-07-19 at 2 22 27 PM](https://private-user-images.githubusercontent.com/7181610/350516939-64cb8b01-9f2a-486d-b278-cfef5037d38d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MjA2NzQsIm5iZiI6MTcyMTQyMDM3NCwicGF0aCI6Ii83MTgxNjEwLzM1MDUxNjkzOS02NGNiOGIwMS05ZjJhLTQ4NmQtYjI3OC1jZmVmNTAzN2QzOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTlUMjAxOTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzhlNzA1ZjAxN2VmMWQzOGM0YzRhNzYxZTk2M2IzMTkyZmMzNTljZjczODQyYTYxNWIyYmJiYjgxMTE3NTcyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1Pw4X9dZHosPpztKkYslRt_os8OQIMN62Cz5_1lNeZA) ![Screenshot 2024-07-19 at 2 22 50 PM](https://private-user-images.githubusercontent.com/7181610/350516971-79682144-0305-43dd-a8b7-0dbb67610c21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MjA2NzQsIm5iZiI6MTcyMTQyMDM3NCwicGF0aCI6Ii83MTgxNjEwLzM1MDUxNjk3MS03OTY4MjE0NC0wMzA1LTQzZGQtYThiNy0wZGJiNjc2MTBjMjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTlUMjAxOTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjJhZTIwOTQ5ZmQ4NjhiOTEwZWFhZTZlYmQ5ODAyMzRhMDc1YjVjZjYzNzljNzYwODNjNTdjZmI2YmE4OTM5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.727quIpZGW6yZmvixA2va4nj5-_0ziXk8jDLgUwaIDw)

@jakesmith once we get dafilesrv instrumentation we'll be able to track these transactions end-to-end. We're able to deploy small, local Elastic stack based trace aggregator which would be very helpful in the instrumentation process. We can share that info if interested.

2024-07-19 20:22 UTC, merged