HPCC4J-667 DFSClient: Request traceparents should use active span
hpcc-systems/hpcc4j pull request #777
Opened 2024-12-03 14:13 UTC by jpmcmu

- Changed RowServiceInputStream to use the active span instead of the top level read span for the traceparent on requests

Signed-off-by: James McMullan James.McMullan@lexisnexis.com

## Type of change:
- [X] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [X] I have created a corresponding JIRA ticket for this submission
- [X] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [X] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [X] The change has been fully tested:
  - [ ] This change does not cause any existing JUnits to fail.
  - [ ] I have include JUnit coverage to test this change
  - [ ] I have performed system test and covered possible regressions and side effects.
- [X] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] This change fixes the problem, not just the symptom

## Testing:

2024-12-03 17:48 UTC, rpastrana requested changes
@jpmcmu a couple of comments

2024-12-03 17:48 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
> -    public static final int          DEFAULT_READ_REQUEST_SPAN_BATCH_SIZE = 25;
this should be reverted

2024-12-03 17:48 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
> +        if (span != null) {
minor formatting issue

2024-12-03 17:48 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
> +        String traceContextHeader = null;
I believe getTraceParentHeader will return null if span == null, or invalid. It feels a little cleaner if we change all these call to gettraceparentheader to:

String traceContextHeader = org.hpccsystems.ws.client.utils.Utils.getTraceParentHeader(versionSpan);

2024-12-03 17:48 UTC, rpastrana commented on dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
> +            traceContextHeader = org.hpccsystems.ws.client.utils.Utils.getTraceParentHeader(span);
I believe you noticed an issue where traceparentheader flags were inconsistent , is that still an issue we need to address?

2024-12-04 14:35 UTC, jpmcmu commented
Look into changing the default sampling flag in getTraceParentHeader() to 01

2024-12-05 14:01 UTC, jpmcmu commented
@rpastrana pushed up code review changes

2024-12-05 14:24 UTC, rpastrana approved these changes
@jpmcmu looks fine, we'll tackle the inconsistent sampled flags with this jira: https://hpccsystems.atlassian.net/browse/HPCC4J-668

2024-12-10 15:13 UTC, merged